secrets:
  datamed_ssl_cert:
    file: ./ssl/datamed.crt
  datamed_ssl_key:
    file: ./ssl/datamed.key
  dhparam:
    file: ./ssl/dhparam.pem
  postgres_password:
    file: ./secrets/postgres_password.txt
  keycloak_admin_password:
    file: ./secrets/keycloak_admin_password.txt
  minio_access_key:
    file: ./secrets/minio_access_key.txt
  minio_secret_key:
    file: ./secrets/minio_secret_key.txt
  token_key:
    file: ./secrets/token_key.txt

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    secrets:
      - datamed_ssl_cert
      - datamed_ssl_key
      - dhparam
    volumes:
      - type: bind
        source: ./ssl
        target: /etc/ssl/certs
        read_only: true
      - type: bind
        source: ./ssl
        target: /etc/ssl/private
        read_only: true
    depends_on:
      - backend
      - frontend
      - keycloak
      - minio
    networks:
      - datamed-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  backend:
    build:
      context: ./backend
      platforms:
        - linux/amd64
        - linux/arm64
    secrets:
      - postgres_password
      - token_key
      - minio_access_key
      - minio_secret_key
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres@postgres:5432/datamed
      - TOKEN_KEY_FILE=/run/secrets/token_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY_FILE=/run/secrets/minio_access_key
      - MINIO_SECRET_KEY_FILE=/run/secrets/minio_secret_key
      - MINIO_BUCKET=${MINIO_BUCKET}
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - datamed-network
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      - REACT_APP_API_URL=https://localhost/api
      - REACT_APP_KEYCLOAK_URL=https://localhost
      - REACT_APP_KEYCLOAK_REALM=datamed
      - REACT_APP_KEYCLOAK_CLIENT_ID=datamed-client
    depends_on:
      backend:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - datamed-network
    healthcheck:
      test: ["CMD-SHELL", "curl -I http://localhost:3000 | grep -E 'HTTP/1.1 (200|404)' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  postgres:
    image: postgres:15
    secrets:
      - postgres_password
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_MULTIPLE_DATABASES=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    networks:
      - datamed-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    secrets:
      - minio_access_key
      - minio_secret_key
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    entrypoint: ["/bin/sh", "-c", "/secrets-entrypoint.sh minio server /data --console-address ':9001'"]
    volumes:
      - minio_data:/data
      - ./secrets-entrypoint.sh:/secrets-entrypoint.sh:ro
    networks:
      - datamed-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    secrets:
      - keycloak_admin_password
      - postgres_password
    env_file:
      - .env
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_SPI_CORS_DEFAULT_ALLOWED_ORIGINS=https://localhost
      - KC_SPI_CORS_DEFAULT_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - KC_SPI_CORS_DEFAULT_ALLOWED_HEADERS=Authorization,Content-Type,Accept
      - KC_FEATURES=preview
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://localhost/auth
      - KC_HOSTNAME_ADMIN_URL=https://localhost/auth
    entrypoint: ["/bin/sh", "-c", "/secrets-entrypoint.sh keycloak start-dev --import-realm"]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./secrets-entrypoint.sh:/secrets-entrypoint.sh:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - datamed-network
    healthcheck:
      test: ["CMD", "echo", "Keycloak is healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  minio_data:
  backend_logs:

networks:
  datamed-network:
    driver: bridge
